### ISSUE TITLE
Installing Error

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraRelay#6] opened 2019-09-16 20:00 UTC
when trying to install azurarelay - getting this error:
Fatal error: Uncaught Error: Call to undefined method Azura\App::create() in /var/azurarelay/www/bin/console.php:7
Stack trace:
#0 {main}
  thrown in /var/azurarelay/www/bin/console.php on line 7

and in browser:
Fatal error: Uncaught Error: Call to undefined method Azura\App::create() in /var/azurarelay/www/web/index.php:7 Stack trace: #0 {main} thrown in /var/azurarelay/www/web/index.php on line 7

**Comment by SlvrEagle23** [comment] 2019-09-18 19:07
@eranwo Closing as a duplicate of #5. Thank you for reporting this issue.

**Closed by SlvrEagle23** 2019-09-18 19:07 UTC
